name: Publishes website content
run-name: ${{ github.actor }} publishes the website
on: [push]
jobs:
  Publish-Website:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: hugo
          version: 1.0
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: |
          cd ${{ github.workspace }}
          npm install staticrypt
          hugo
          ./joker --version
      - run: echo "ğŸ This job's status is ${{ job.status }}."
